services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RAILS_ENV=development

  worker:
    build: .
    environment:
      - SERVER_URL=http://localhost:8080
    network_mode: "host"
    command: ruby ./post_initialize_request.rb && tail -f /dev/null
