name: Rails Build & Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.5'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec spec/

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start Docker Compose services
        run: docker-compose up -d --build

      - name: Wait for web service to start
        run: sleep 15

      - name: Verify web service is running
        run: |
          curl --fail http://localhost:8080 || exit 1

      - name: Stop and remove Docker Compose services
        run: docker-compose down
